# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$env = <<SCRIPT
echo "export DOCKERHUB_USER=#{ENV['DOCKERHUB_USER']}" >> ~/.profile
echo "export DOCKERHUB_PASS=#{ENV['DOCKERHUB_PASS']}" >> ~/.profile
echo "export DOCKERHUB_MAIL=#{ENV['DOCKERHUB_MAIL']}" >> ~/.profile
SCRIPT

$ubuntu = <<SCRIPT
echo ====> Updating Packages
export DEBIAN_FRONTEND=noninteractive
# -qq is pointless, it doesn't work :S
apt-get update > /dev/null
echo ====> Installing Packages
apt-get install -qq -y --no-install-recommends docker.io openvswitch-switch unzip
ln -s /vagrant/scripts/socketplane.sh /usr/bin/socketplane
cd /usr/bin
wget --quiet https://dl.bintray.com/mitchellh/consul/0.4.1_linux_amd64.zip
unzip *.zip
rm *.zip
cd /vagrant && docker build -q -t socketplane/socketplane .
echo ====> Installing SocketPlane
socketplane install unattended
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Socketplane demo boxes
  num_nodes = (ENV['SOCKETPLANE_NODES'] || 3).to_i
  base_ip = "10.254.101."
  socketplane_ips = num_nodes.times.collect { |n| base_ip + "#{n+21}" }

  num_nodes.times do |n|
    config.vm.define "socketplane-#{n+1}" do |socketplane|
      socketplane.vm.box = "socketplane/ubuntu-14.10"
      socketplane.vm.box_url = "https://socketplane.s3.amazonaws.com/vagrant/virtualbox/ubuntu-14.10.box"
      socketplane_ip = socketplane_ips[n]
      socketplane_index = n+1
      socketplane.vm.hostname = "socketplane-#{socketplane_index}"
      socketplane.vm.network :private_network, ip: "#{socketplane_ip}", virtualbox__intnet: true
      socketplane.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      end
      socketplane.vm.provision :shell, inline: $env
      socketplane.vm.provision :shell, inline: "echo 'export BOOTSTRAP=#{n+1 == 1 ? "true" : "false"}' >> ~/.profile"
      socketplane.vm.provision :shell, inline: $ubuntu
    end
  end
end
